language: node_js
node_js:
  - '6'
sudo: false
script:
    - "npm test"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE think_test;'
after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
